dist: xenial
language: python
cache: pip
python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"
sudo: false

# Define document loaders
env:
  - LOADER=requests
  - LOADER=aiohttp

matrix:
  exclude:
    - python: "2.7"
      env: LOADER=aiohttp
    - python: "pypy"
      env: LOADER=aiohttp
    - python: "3.4"
      env: LOADER=aiohttp

install:
  - pip install -r requirements.txt
  - git clone --depth 1 https://github.com/w3c/json-ld-api.git _json-ld-api
  - git clone --depth 1 https://github.com/w3c/json-ld-api.git _json-ld-framing
  #- git clone --depth 1 https://github.com/json-ld/json-ld.org.git _json-ld.org
  - git clone --depth 1 https://github.com/json-ld/normalization.git _normalization

# Download test suite and run tests... submodule? meta testing project with
# all of the reference implementations?
script: 
  - python tests/runtests.py -d ./_json-ld-api/tests -l $LOADER
  - python tests/runtests.py -d ./_json-ld-framing/tests -l $LOADER
  #- python tests/runtests.py -d ./_json-ld.org/test-suite -l $LOADER
  - python tests/runtests.py -d ./_normalization/tests -l $LOADER

notifications:
  email:
    on_success: change
    on_failure: change
