language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# no requirements, but simulate what a user would see
install: pip install .
# download test suite and run tests... submodule? meta testing project with
# all of the reference implementations?
script: 
  - git clone https://github.com/json-ld/json-ld.org.git spec
  - python tests/runtests.py -d spec/test-suite
notifications:
  email:
    on_success: change
    on_failure: change
